/* Information Tooltip Framework (spec §17).
   Every cross-system metric maps to: source systems, calculation logic,
   and business interpretation. Keyed by a short metric id. */

export const METRICS = {
  revenue: {
    name: "Revenue (30 days)",
    sources: ["Shopify", "WooCommerce", "QuickBooks"],
    logic: "Sum of order subtotals less discounts across all sales channels in the trailing 30 days.",
    meaning: "Top-line demand. The starting point for every profitability calculation downstream.",
  },
  grossProfit: {
    name: "Gross Profit",
    sources: ["Shopify", "QuickBooks"],
    logic: "Revenue minus Cost of Goods Sold (COGS) pulled from QuickBooks landed costs.",
    meaning: "Money left after product cost — before marketing and overhead.",
  },
  marketingSpend: {
    name: "Marketing Spend",
    sources: ["Meta Ads", "Google Ads", "TikTok Ads", "Klaviyo"],
    logic: "Total advertising spend aggregated across every connected ad platform for the period.",
    meaning: "The cost of acquiring and retaining demand. Compared against the revenue it drives.",
  },
  netProfit: {
    name: "Net Profit",
    sources: ["Shopify", "QuickBooks", "Meta Ads", "Google Ads"],
    logic: "Gross Profit minus total Marketing Spend for the period.",
    meaning: "True profit contribution after the two largest variable costs. The number that matters.",
  },
  orders: {
    name: "Orders",
    sources: ["Shopify", "WooCommerce"],
    logic: "Count of placed orders across storefronts in the trailing 30 days.",
    meaning: "Transaction volume. Paired with AOV to understand revenue movement.",
  },
  returningPct: {
    name: "Returning Customer %",
    sources: ["Shopify", "Recharge"],
    logic: "Share of orders placed by customers with a prior purchase.",
    meaning: "Loyalty signal. Higher repeat share lowers blended acquisition cost.",
  },
  roas: {
    name: "ROAS",
    sources: ["Meta Ads", "Google Ads", "TikTok Ads", "GA4"],
    logic: "Attributed revenue divided by ad spend, blended across paid channels.",
    meaning: "Advertising efficiency. Below ~1.4x typically means the channel loses money after COGS.",
  },
  cac: {
    name: "Customer Acquisition Cost",
    sources: ["Meta Ads", "Google Ads", "TikTok Ads", "Shopify"],
    logic: "Total ad spend divided by newly acquired customers in the period.",
    meaning: "What it costs to win a customer. Must stay well below LTV to be sustainable.",
  },
  ltv: {
    name: "Customer Lifetime Value",
    sources: ["Shopify", "Klaviyo", "Recharge"],
    logic: "Average total revenue per customer across their full purchase history.",
    meaning: "How much a customer is worth over time. Sets the ceiling for acquisition spend.",
  },
  convRate: {
    name: "Conversion Rate",
    sources: ["GA4", "Shopify"],
    logic: "Purchases divided by sessions across the storefront.",
    meaning: "Storefront and offer effectiveness at turning traffic into orders.",
  },
  grossMargin: {
    name: "Gross Margin",
    sources: ["Shopify", "QuickBooks"],
    logic: "Gross Profit as a percentage of Revenue.",
    meaning: "Pricing power and product economics. Erodes when discounting or costs rise.",
  },
  netMargin: {
    name: "Net Margin",
    sources: ["QuickBooks", "Ad Platforms"],
    logic: "Net Profit as a percentage of Revenue.",
    meaning: "Overall profitability after product and marketing costs.",
  },
  revenueAtRisk: {
    name: "Revenue at Risk",
    sources: ["Shopify", "Meta Ads", "Inventory Engine"],
    logic: "Revenue generated by products projected to stock out within 14 days, at current velocity.",
    meaning: "Potential future revenue lost if inventory is not replenished in time.",
  },
  stockoutRisk: {
    name: "Stockout Risk",
    sources: ["Shopify", "Inventory Engine", "Supplier Data"],
    logic: "Products whose days-of-stock (units ÷ daily velocity) fall inside the lead-time window.",
    meaning: "SKUs likely to sell out before a reorder can arrive — lost sales risk.",
  },
  overstockRisk: {
    name: "Overstock Risk",
    sources: ["Shopify", "Inventory Engine"],
    logic: "Products with more than ~180 days of inventory at current velocity.",
    meaning: "Working capital trapped in slow inventory; candidates for clearance.",
  },
  daysOfInventory: {
    name: "Days of Inventory",
    sources: ["Shopify", "Inventory Engine"],
    logic: "Units in stock divided by average daily units sold.",
    meaning: "How long current stock lasts. Balances stockout risk against tied-up capital.",
  },
  repeatRate: {
    name: "Repeat Purchase Rate",
    sources: ["Shopify", "Klaviyo", "Recharge"],
    logic: "Share of customers with two or more orders.",
    meaning: "Retention strength. Repeat buyers carry far higher margins than new ones.",
  },
  churnRisk: {
    name: "Churn Risk",
    sources: ["Shopify", "Klaviyo", "Gorgias"],
    logic: "Composite score from purchase recency, frequency, and engagement decline.",
    meaning: "Customers likely to lapse. Targets for proactive win-back outreach.",
  },
  returnRate: {
    name: "Return Rate",
    sources: ["ShipStation", "Shopify", "Gorgias"],
    logic: "Returned orders divided by total fulfilled orders for the period.",
    meaning: "Quality and sizing signal. Directly erodes net margin.",
  },
  fulfillmentTime: {
    name: "Fulfillment Time",
    sources: ["ShipStation", "Shopify"],
    logic: "Average hours from order placement to carrier handoff.",
    meaning: "Operational speed. Faster fulfillment lifts satisfaction and reduces support load.",
  },
  inventoryValue: {
    name: "Inventory Value",
    sources: ["Shopify", "QuickBooks"],
    logic: "Sum of on-hand units multiplied by landed unit cost.",
    meaning: "Total capital currently tied up in stock.",
  },
  profitByChannel: {
    name: "Profit by Channel",
    sources: ["Shopify", "Ad Platforms", "QuickBooks"],
    logic: "Gross profit attributed to each acquisition channel after channel-level ad cost.",
    meaning: "Which channels actually make money — not just which drive revenue.",
  },
};

export function getMetric(id) {
  return METRICS[id] || null;
}
